services:
  dev:
    container_name: iii-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    image: "iii_drone_dev:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/hosts:/etc/hosts
      - .:/home/iii/ws:cached
      - /dev:/dev
      - /run/user/1000/at-spi/bus_1:/run/user/1000/at-spi/bus_1
      - $XAUTHORITY:$XAUTHORITY
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    environment:
      - ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=$XAUTHORITY
    security_opt:
      - apparmor:unconfined
    privileged: true
    ipc: host
    pid: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
