services:
  colcon_build:
    container_name: iii-colcon-build

    build:
      context: ..
      dockerfile: docker/Dockerfile.colcon_build

    image: iii_drone:colcon_build

    volumes:
      - ..:/home/iii/ws:cached

    command: sleep infinity

    depends_on:
      - base

    networks:
      - iii_drone

networks:
  iii_drone:
    external: true
