include:
  - "system/docker-compose.configuration.yml"
  - "system/docker-compose.micro-ros-agent.yml"
  - "system/docker-compose.sensors-sim.yml"
  - "system/docker-compose.tf-sim.yml"
  - "system/docker-compose.perception.yml"
  - "system/docker-compose.control.yml"