ARG ROS_DISTRO

# Use an official ROS2 base image
FROM ros:${ROS_DISTRO}

# Install necessary packages and dependencies
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip

RUN apt-get update && apt-get upgrade -y

# # Set the working directory
WORKDIR /home/ws

# Install dependencies
COPY src/III-Drone-Core/scripts /scripts
RUN /scripts/install_dependencies.sh
RUN rm -rf /scripts