include:
  - ../docker/docker-compose.base.yml

services:
  dev:
    container_name: iii-dev
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

      # args:
      #   username: ${USER}

    image: iii_drone:dev

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/home/iii/ws:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    depends_on:
      - base

    # # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined