services:
  sensors:
    image: "iii_drone:exec_base"
    volumes:
      - ..:/home/ws:cached
    command: ros2 launch iii_drone_core sensors.launch.py ${SENSORS_ARGS}
    depends_on:
      - exec_base