services:
  configuration-server:
    container_name: configuration-server
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    image: "iii_drone:base"
    volumes:
      - ../..:/home/iii/ws:cached
    command: ros2 run iii_drone_configuration configuration_server_node.py --ros-args --params-file ${CONFIG_BASE_DIR}/iii_drone/ros_params.yaml
    environment:
      - CONFIG_BASE_DIR
    # networks:
    #   - ${COMPOSE_PROJECT}_default