SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

export NODE_MANAGEMENT_CONFIG_DIR="$WORKSPACE_DIR/src/III-Drone-Supervision/node_management_config"
export CONFIG_BASE_DIR="$WORKSPACE_DIR/.config"
export SIMULATION_CONFIG_DIR="$WORKSPACE_DIR/tools/simulation"
export III_SYSTEM_RUNTIME_DIR="$WORKSPACE_DIR/runtime"
export III_SYSTEM_DAEMON_SOCKET="$III_SYSTEM_RUNTIME_DIR/system_manager.sock"
export III_SYSTEM_DAEMON_LOG="$III_SYSTEM_RUNTIME_DIR/system_manager.log"
export III_SYSTEMD_DAEMON_SERVICE="iii-system-daemon.service"
