/control/maneuver_controller/combined_drone_awareness
/control/maneuver_controller/current_maneuver
/control/maneuver_controller/maneuver_queue
/control/maneuver_controller/reference
/control/maneuver_controller/reference_callback_provider
/control/maneuver_controller/target
/control/maneuver_controller/target_drone_pose
/control/maneuver_controller/target_pose

/control/trajectory_controller/target_pose
/control/trajectory_controller/trajectory_path
/control/trajectory_generator/target_pose
/control/trajectory_generator/trajectory_path

/fmu/out/vehicle_odometry
/fmu/out/vehicle_status

/mission/mission_executor/maneuver_reference_client/reference_mode

/mission/powerline_overview_provider/powerline_overview_provider/transition_event
/mission/powerline_overview_provider/stored_powerline_points
/mission/powerline_overview_provider/stored_powerline_pose
/mission/powerline_overview_provider/stored_powerline_status

/payload/charger_gripper/battery_voltage
/payload/charger_gripper/charger_operating_mode
/payload/charger_gripper/charger_status
/payload/charger_gripper/charging_power
/payload/charger_gripper/gripper_status

/perception/hough_transformer/cable_yaw_angle
/perception/hough_transformer/status

/perception/pl_dir_computer/powerline_direction_pose
/perception/pl_dir_computer/powerline_direction_quat
/perception/pl_dir_computer/status

/perception/pl_mapper/points_est
/perception/pl_mapper/powerline
/perception/pl_mapper/projected_points
/perception/pl_mapper/state
/perception/pl_mapper/transformed_points

/sensor/cable_camera/image_raw

/sensor/mmwave/pcl

/tf
/tf_static